
package esbam.canoa123.views;

import esbam.canoa123.model.Barcos;
import esbam.canoa123.model.Usuario;
import java.awt.Color;


public class Tela_Principal extends javax.swing.JFrame {
           
            
    /**
     * Creates new form Tela_Principal2
     */
    public Tela_Principal() {
        initComponents();
         setLocationRelativeTo(null);
        getContentPane().setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadBarcos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        cadPassageiros = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuCidade = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuCadCategorias = new javax.swing.JMenuItem();
        menuPassageiros = new javax.swing.JMenuItem();
        menuCidades = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo 123canoa.jpeg"))); // NOI18N

        cadBarcos.setText("Cadastros");
        cadBarcos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadBarcosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Barcos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        cadBarcos.add(jMenuItem1);

        cadPassageiros.setText("Passageiros");
        cadPassageiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPassageirosActionPerformed(evt);
            }
        });
        cadBarcos.add(cadPassageiros);

        jMenuItem4.setText("Categoria");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        cadBarcos.add(jMenuItem4);

        menuCidade.setText("Cidade");
        menuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadeActionPerformed(evt);
            }
        });
        cadBarcos.add(menuCidade);

        jMenuBar1.add(cadBarcos);

        jMenu2.setText("Pesquisar");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Barcos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuCadCategorias.setText("Categorias");
        menuCadCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadCategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(menuCadCategorias);

        menuPassageiros.setText("Passageiros");
        menuPassageiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPassageirosActionPerformed(evt);
            }
        });
        jMenu2.add(menuPassageiros);

        menuCidades.setText("Cidades");
        menuCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadesActionPerformed(evt);
            }
        });
        jMenu2.add(menuCidades);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Alterar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu5.setText("Excluir");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarNome(){
        Usuario usu = new Usuario();
        usu.getNome_usuario();
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastrarBarcos tlCBarcos = new TelaCadastrarBarcos();
        tlCBarcos.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cadPassageirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPassageirosActionPerformed
        TelaCadastrarPassageiros tlPas = new TelaCadastrarPassageiros();
        tlPas.setVisible(true);
        
    }//GEN-LAST:event_cadPassageirosActionPerformed

    private void cadBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadBarcosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadBarcosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        TelaCadastroCategoria telCat = new TelaCadastroCategoria();
        telCat.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        TelaConsultaBarcos telaConsBarc = new TelaConsultaBarcos();
        telaConsBarc.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuCadCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadCategoriasActionPerformed
        // TODO add your handling code here:
        TelaConsultaCategoria tc = new TelaConsultaCategoria();
        tc.setVisible(true);
    }//GEN-LAST:event_menuCadCategoriasActionPerformed

    private void menuPassageirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPassageirosActionPerformed
        // TODO add your handling code here:
        TelaConsultaPassageiros tp = new TelaConsultaPassageiros();
        tp.setVisible(true);
    }//GEN-LAST:event_menuPassageirosActionPerformed

    private void menuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadeActionPerformed
        // TODO add your handling code here:
        TelaCadastrarCidade tc = new TelaCadastrarCidade();
        tc.setVisible(true);
    }//GEN-LAST:event_menuCidadeActionPerformed

    private void menuCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadesActionPerformed
        // TODO add your handling code here:
        TelaConsultaCidades tc = new TelaConsultaCidades();
        tc.setVisible(true);
        
    }//GEN-LAST:event_menuCidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cadBarcos;
    private javax.swing.JMenuItem cadPassageiros;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuCadCategorias;
    private javax.swing.JMenuItem menuCidade;
    private javax.swing.JMenuItem menuCidades;
    private javax.swing.JMenuItem menuPassageiros;
    // End of variables declaration//GEN-END:variables
}
